default:
  image: maven:3-openjdk-11-slim

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - dockerize
  
build:
  stage: build
  script:
    - mvn compile
     
test:
  stage: test
  script:
    - mvn test

dockerize:
  stage: dockerize
  image: docker:latest
  services:
    - docker:dind
  script:
    #- apk update
    #- apk add docker-compose
    - docker login -u $DOCKER_USER -p $DOCKER_TOKEN registry.gitlab.com
    #- docker-compose build
    - docker build -t registry.gitlab.com/lbovolini/todo .
    - docker push registry.gitlab.com/lbovolini/todo
