version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=todo
    ports:
      - 27017:27017
    network_mode: host
    volumes:
      - $HOME/mongo:/data/db
    healthcheck:
      test: "exit 0"
  api:
    build: .
    image: todo-api
    depends_on:
      - mongo
    network_mode: "host"
    hostname: localhost
    restart: always
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/todo
    ports:
      - 8080:8080
    healthcheck:
      test: "exit 0"
