version: '3.8'

services:
  todo_api:
    build: .
    image: todo-api
    container_name: todo_api_container
    user: user
    depends_on:
      - todo_mongo
    restart: unless-stopped
    environment:
      - SPRING_DATA_MONGODB_DATABASE=todo
      - SPRING_DATA_MONGODB_HOST=todo_mongo
      - SPRING_DATA_MONGODB_URI=mongodb://todo_mongo:27017/todo
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
    ports:
      - 8080:8080
    healthcheck:
      test: "exit 0"

  todo_mongo:
    image: mongo:latest
    container_name: todo_mongo_container
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=todo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db:rw
    healthcheck:
      test: "exit 0"

